version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: collabcanvas-postgres
    environment:
      POSTGRES_DB: collabcanvas_local
      POSTGRES_USER: collabcanvas
      POSTGRES_PASSWORD: collabcanvas123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U collabcanvas -d collabcanvas_local"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    container_name: collabcanvas-backend
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://collabcanvas:collabcanvas123@postgres:5432/collabcanvas_local
      - SECRET_KEY=local-development-secret-key
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001,http://localhost:3002,http://localhost:5173
      # Firebase configuration (using production values for local testing)
      - FIREBASE_PROJECT_ID=collabcanvas-24-mvp
      - FIREBASE_CLIENT_EMAIL=firebase-adminsdk-fbsvc@collabcanvas-24-mvp.iam.gserviceaccount.com
      - FIREBASE_PRIVATE_KEY_ID=70025e873e41f61c9eb4137038b1d420a669626b
      - FIREBASE_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC56nl49eeKf2VY\nInaDNMSojgjQOxF5n4Ex1TNe3tcwYEMkTIrO+y7hqsewL+xeXFP53ueWuzOMWfGE\n6DkOvVOTwXtB33JpeLZo0Iww5uRfsBlJX5M0E+/lImi7xwBnLdd9bcjHmMAvvhS4\nL21tuv7NWR2j2khQ5kFsg40xUJMzRAWOt5Yp8tWsu3iRk7eoS+xZDCQwoYERlTGm\nyN3sKcY6U/AdnJkWVO5crWc40xjDnOgk5mkLyLW9XI4KPTh1vMqYKild/gkJ8Qe5\niRxa1hFAK1+Fv+nofuNwW4wV+kbuzo3VI+8g+bPKBABQvRy3G4v2bY1dlN7xD0x0\ntQklKb9fAgMBAAECggEADqLyiD7XyTQJXvxrlx3G47w23mngENKpYap2vl/N0i2p\n64gpH21v/e0rhmfndHBRXikZ02iOgNyt4nhD0bC/DTFcyk1UnRAXUD4m40yyKwRa\noUeod5+gMcpZM3tRwU2/Gs1TUr9oVfnheLSnKU3g9HqxFi6/pbrS6L+clIbS5+Sv\nL4H54aWj56QEoPrgDAw2uRRBpHJ+RWraoGbHE7NFRVyrJ9DAUBp6iehtiKq3DrK4\nIbXhASHS1EXWBbuQPs6wh+o8pmoljJfq0pp7oPgSziqBGclwYWONaN6Ggep7rEkh\nw4+WUKTrT2hqpnOcobbfU9//FjCcL92tWQYkl0GgKQKBgQDauHMC/v9RaE4mZ2XJ\nSxkXCA1MiKA8DLKcWgIpa7noFV7od9CtN2T6Gjj4x/ik4RNrMCkIvZZ04R4E9D+Y\nfs65dROWpmx125GLcw8Y7vcE4KNG9UPExpoGz0A2NUukv0OaSfxg+hnR/FKra38P\n2wQrYFGV54B7pAv1An9tSpe1ZwKBgQDZmqUPoF6J1dWHTg1uNOV9zUmhHendP8ZG\nPzxGLc6c/YoN5nPR1Dr34yRNcNDwmiG/OSlOyj90Fdd3RRkWzd/70j+acygXLQKb\nL5An6s6P0nRcIOsuGMrlsDfrzIm9HVFxSfCo9V6oAg1rFLaKn4iG+lHnB1lcpz+q\nXw7AuXCzSQKBgQCXFejkve7ydiHd53jpZsXrIfXF028UbBUJaie0Iy8lgXWxEesF\nbImFNo36VHCOvKekWH1P+16uWD9bXrl3hsUYWSZx3352n3jXomBgcdoS9XX0c0If\n8Ky/XXTWvVQGdtSlBMyg1ML3Sdx1a2k3M6yapgtViLg5MGXOFq6deXR4qwKBgBaD\nBSiEssMXuCtzS7hnCIbnQgLFEXiuLFkAGcA45PMg17Nwb/L5PdB/UzYfwb3idDNQ\nOpHIIqBj0hKot1vAmLd4nNPhrfgX0/kyBnvastv2LcuKLEpsjjEM9fwTAPzrl41c\n1OTl3ZEMBU9aqTfWIU21f9uiyv/m3ZNGmkQd6ybhAoGAOzS1LY4Z6otzjfHkFV+z\nVgJeDOhalk5apvRIGychrducvkXJ8EH4uq31RYN6B3BVg5zDojWF2ak+9gYH2Op6\nFUWkvEMWAqEB73u/NwTyNPLxiqbdn2FAQ5SVHh4XDH4r9+8vuovrssppH3a2/5WG\nK+yH/XKNSsWqgM31mOq51co=\n-----END PRIVATE KEY-----
      - FIREBASE_CLIENT_ID=113427911244146012632
      - FIREBASE_AUTH_URI=https://accounts.google.com/o/oauth2/auth
      - FIREBASE_TOKEN_URI=https://oauth2.googleapis.com/token
      - FIREBASE_AUTH_PROVIDER_X509_CERT_URL=https://www.googleapis.com/oauth2/v1/certs
      - FIREBASE_CLIENT_X509_CERT_URL=https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40collabcanvas-24-mvp.iam.gserviceaccount.com
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: python run_local.py

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    container_name: collabcanvas-frontend
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_SOCKET_URL=http://localhost:5000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
