[build]
builder = "python"
buildCommand = "cd backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && ./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[python]
version = "3.9"
requirementsFile = "backend/requirements.txt"
