# Railway NIXPACKS configuration for backend Python Flask application
# This config is used when root directory is set to "backend"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install --no-cache-dir --disable-pip-version-check -r requirements.txt"
]

[phases.build]
cmds = [
  "python -m py_compile run.py",
  "python -m py_compile app/__init__.py"
]

[start]
cmd = "python run.py"

[variables]
FLASK_APP = "run.py"
FLASK_ENV = "production"
PYTHONPATH = "/app"
PORT = "5000"
PYTHONUNBUFFERED = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
PIP_NO_CACHE_DIR = "1"
