[build]
builder = "python"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[python]
version = "3.9"
requirementsFile = "requirements.txt"
