# Prometheus Configuration for CollabCanvas
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'collabcanvas'
    environment: 'production'

rule_files:
  - "alerts/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # CollabCanvas Backend
  - job_name: 'collabcanvas-backend'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # CollabCanvas Frontend
  - job_name: 'collabcanvas-frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Node Exporter (System metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

  # cAdvisor (Container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s

  # WebSocket connections
  - job_name: 'websocket-metrics'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/metrics/websocket'
    scrape_interval: 5s

  # API endpoints
  - job_name: 'api-metrics'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/metrics/api'
    scrape_interval: 5s

  # Test execution metrics
  - job_name: 'test-metrics'
    static_configs:
      - targets: ['test-runner:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Health checks
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'backend:5000'
        - 'frontend:80'
        - 'redis:6379'
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 5s
